name: Upload Sphinx Documentation

on:
  push:
    branches:
     - kr/documentation/*
    tags:
     - '*'  # Trigger on any tag push
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: v0.0.0+githubActionDefault
    outputs:
      tag_name: ${{ steps.final_tag.outputs.TAG_NAME }}
    steps:
      - name: Extract tag name, if it exists
        id: tag_extraction
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
      - name: Return tag name as an output
        id: final_tag
        run: echo "TAG_NAME=${{ env.TAG_NAME }}" >> "$GITHUB_OUTPUT"

  docs:
    runs-on: ubuntu-latest
    needs: extract-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install Sphinx dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx_copybutton furo
      - name: Install Brom dependencies
        run: pip install -r requirements.txt
      - name: Update version in setup.py
        run: >-
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ needs.extract-tag.outputs.tag_name }}/g" setup.py
      - name: Install package
        run: pip install -e .
      - name: Sphinx build
        run: |
          cd docs && make generate-and-build-docs BROM_VERSION=${{ needs.extract-tag.outputs.tag_name }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
          # `force_orphan: true