name: Upload Sphinx Documentation

on:
  push:
    branches:
      - main
      - kr/documentation/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.TAG_NAME }}
    steps:
      - name: Extract tag name
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=$(if [[ $GITHUB_REF == refs/tags/* ]]; then echo $GITHUB_REF | cut -d / -f 3; else echo 'latest'; fi)" >> $GITHUB_OUTPUT

  docs:
    runs-on: ubuntu-latest
    needs: extract-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install Sphinx dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Update version in setup.py
        run: >-
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ needs.extract-tag.outputs.tag_name }}/g" setup.py
      - name: Install package
        run: pip install -e .
      - name: Sphinx build
        run: |
          cd docs && make generate-and-build-docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          # `force_orphan: true